### ISSUE TITLE
I can't receive message when i use the newest libcapn?

### ISSUE THREAD

**Issue by fdxuwei** [adobkin/libcapn#13]
I can success push and receive message when i use libcapn of version 1.0.0, but when I use the version 1.0.0berta3 , I send a message by the example code in send_push.c,  no error message printed, but my iphone  receive no  message.

**Comment by adobkin** [comment]
You need compile and install libcapn from sources (master branch). Version 1.0.0 does not support TLS connection.
see https://developer.apple.com/news/?id=10222014a
see https://github.com/adobkin/libcapn/commit/3546927c3ad5e0f02180f7010afcffde4e7d4139

**Comment by fdxuwei** [comment]
I tried the source of master branch, but it still dosen't work.

**Comment by adobkin** [comment]
Please try v2.0.0, it work fine
