### ISSUE TITLE
install error as below

### ISSUE THREAD

**Issue by tetang1230** [adobkin/libcapn#18]
The output was:
1
cc: error: x86_64: No such file or directory
cc: error: unrecognized command line option ‘-arch’
cc: error: unrecognized command line option ‘-no-cpp-precomp’

Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
cc: error: x86_64: No such file or directory
cc: error: unrecognized command line option ‘-arch’
cc: error: unrecognized command line option ‘-no-cpp-precomp’
cc: fatal error: no input files
compilation terminated.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

And i used ubuntu 

uname -a

Linux chester-ubuntu 3.19.0-41-generic #46-Ubuntu SMP Fri Dec 4 18:18:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by adobkin** [comment]
You use IAR Compiler, but libcapn not supported it. Use gcc or clang
