### ISSUE TITLE
Build problem referencing fcntl.h in apn.c

### ISSUE THREAD

**Issue by hunger1** [adobkin/libcapn#22]
apn.c should reference `<fcntl.h>`, not `<sys/fcntl.h>`. There is no `<sys/fcntl.h>` on some POSIX systems but you are guaranteed to have `<fcntl,h>` on all POSIX systems. If you do "man fcntl" on HP-UX, Linux , Mac OS X, and Solaris systems, it says to use `<fcntl.h>`.

Requires changing:

`CHECK_INCLUDE_FILES (sys/fcntl.h APN_HAVE_SYS_FCNTL_H)`

to:

`CHECK_INCLUDE_FILES (fcntl.h APN_HAVE_FCNTL_H)`

in CMakeLists.txt

and 

`#ifdef APN_HAVE_SYS_FCNTL_H`
`#include <sys/fcntl.h>`

to

`#ifdef APN_HAVE_FCNTL_H`
`#include <fcntl.h>`

in apn.c

This change will also make it match jansson, which has:

`check_include_files (fcntl.h HAVE_FCNTL_H)`

**Comment by adobkin** [comment]
Fixed, tnx!
