### ISSUE TITLE
Invalid checking certificate

### ISSUE THREAD

**Issue by cuongtv51** [adobkin/libcapn#26]
I just pull new code, and create 1 certificate for push voip (using PushKit), 
but when i run it, it log

[inf] Initializing SSL connection...
[inf] Local certificate subject: UID=xxx.voip, CN=VoIP Services: xxx, OU=GH99A265HF, O=NGO LOC, C=US
[inf] Local certificate issuer: C=US, O=Apple Inc., OU=Apple Worldwide Developer Relations, CN=Apple Worldwide Developer Relations Certification Authority
[err] Invalid certificate. You are using a SANDBOX mode, but certificate was created for usage in PRODUCTION

I just check code, and see in file apn_ssl.c (line 219) you have check certificate subject CN, but i think do we need check this ? or may be apple has some new subject CN in future time.

**Comment by ajayvegita** [comment]
hi, any update on above issue. I am also facing the same issue.

**Comment by adobkin** [comment]
Yes, I fix it within several days

**Comment by ajayRam2020** [comment]
Temporary workaround: 

1. Comment  "if(cn) { ... }"  statement from apn_ssl.c [line 233-248].

**Comment by adobkin** [comment]
> I just check code, and see in file apn_ssl.c (line 219) you have check certificate subject CN, but i think do we need check this ? or may be apple has some new subject CN in future time.

Yes, comparing CN is bad way. Now, library checks extensions of certificate:

```
#define APN_CERT_EXTENSION_PRODUCTION "1.2.840.113635.100.6.3.2"
#define APN_CERT_EXTENSION_SANDBOX    "1.2.840.113635.100.6.3.1"
```
