### ISSUE TITLE
apn_payload_add_custom_property_integer() returns an error if the integer value is zero

### ISSUE THREAD

**Issue by legakis** [adobkin/libcapn#7]
It looks like this code:

    if (!property_value) {
        APN_SET_ERROR(error, APN_ERR_INVALID_ARGUMENT | APN_ERR_CLASS_USER, "value of custom property is NULL");
        APN_RETURN_ERROR;
    }

was copy-and-pasted from apn_payload_add_custom_property_string()

**Comment by adobkin** [comment]
Fixed. Tnx
